apiVersion: apps/v1
kind: Deployment
metadata:
  name: coconote-backend
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: coconote-backend
          image: 730335516193.dkr.ecr.ap-northeast-2.amazonaws.com/coconote/coconote_be:SET_ME_LATER  # dynamic 최신 태그로 설정
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev  # dev 환경 설정을 사용-
