# k8s/overlays/prod/deployment-patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coconote-backend
spec:
  replicas: 3  # Prod 환경에서는 더 높은 가용성을 위해 3개로 설정
  template:
    spec:
      containers:
        - name: coconote-backend
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev