server:
  port: 8080

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
    suffix: .ftl
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${local.datasource.url}
    username: ${local.datasource.username}
    password: ${local.datasource.password}
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show_sql: true
    open-in-view: false

springdoc:
  api-docs:
    groups:
      enabled: true
  #    path: /api-docs
  cache:
    disabled: true
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC


aws:
  accessKeyId: ${local.s3.key}
  secretKey: ${local.s3.secret}
  s3:
    region: ${local.s3.region}
    bucket: ${local.s3.bucket}