server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${local.datasource.url}
    username: ${local.datasource.username}
    password: ${local.datasource.password}
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show_sql: true
    open-in-view: false
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 300000

springdoc:
  api-docs:
    groups:
      enabled: true
  #    path: /api-docs
  cache:
    disabled: true
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC


aws:
  access_key_id: ${local.s3.key}
  secret_key: ${local.s3.secret}
  s3:
    region: ${local.s3.region}
    bucket: ${local.s3.bucket}