# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coconote-backend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coconote-backend
  template:
    metadata:
      labels:
        app: coconote-backend
    spec:
      containers:
        - name: coconote-backend
          image: 730335516193.dkr.ecr.ap-northeast-2.amazonaws.com/coconote/coconote_be:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: coconote-backend-secrets  # Kubernetes Secret 참조
