name: CI/CD Pipeline for Prod

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때만 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR with Jib
        run: |
          IMAGE_TAG="latest"
          ./gradlew jib --image=730335516193.dkr.ecr.ap-northeast-2.amazonaws.com/coconote/coconote_be:$IMAGE_TAG

  update-kustomize-prod:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Kustomize deployment image for Prod
        run: |
          IMAGE_TAG="latest"
          # Prod 환경의 deployment-patch.yml 파일에서 이미지 태그 업데이트
          sed -i 's|image: 730335516193.dkr.ecr.ap-northeast-2.amazonaws.com/coconote/coconote_be:.*|image: 730335516193.dkr.ecr.ap-northeast-2.amazonaws.com/coconote/coconote_be:'$IMAGE_TAG'|' k8s/overlays/prod/deployment-patch.yml
          
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add k8s/overlays/prod/deployment-patch.yml
          git commit -m "Update prod image tag to $IMAGE_TAG"
          git push

      - name: Restart Kubernetes Deployment to Pull Latest Image
        run: |
          kubectl rollout restart deployment coconote-backend -n default  # 쿠버네티스에서 강제로 새 이미지 가져오기
