name: CI/CD Pipeline for Prod

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때만 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR with Jib
        env:
          IMAGE_URI: 730335516193.dkr.ecr.ap-northeast-2.amazonaws.com/coconote/coconote_be
        run: |
          ./gradlew jib --image=$IMAGE_URI:latest
          ./gradlew jib --image=$IMAGE_URI:${{ github.sha }}

          - name: Update Deployment.yaml with new image tag
            run: |
              sed -i "s|image: $IMAGE_URI:.*|image: $IMAGE_URI:${{ github.sha }}|" k8s/overlays/prod/deployment.yaml

          - name: Commit and push updated Deployment.yaml
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: |
              git config --local user.name "github-actions[bot]"
              git config --local user.email "github-actions[bot]@users.noreply.github.com"
              git add k8s/overlays/prod/deployment.yaml
              git commit -m "Update image tag to $IMAGE_URI:${{ github.sha }}"
             git push origin main